In [45]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

import warnings
warnings.filterwarnings('ignore')

In [46]:
import 특이점장전ver4
import imp
imp.reload(특이점장전ver4)
from 특이점장전ver4 import Singularity
sl = Singularity()

In [47]:
default_date = datetime.strptime('2007-06-01', '%Y-%m-%d')  # 초기 시간(2007년7월1일)

In [48]:
data1 = pd.read_csv('./datasets/kospi_close.csv')
data1.set_index('time', inplace=True)
data1.index = pd.to_datetime(data1.index)
data1.index = pd.to_datetime(data1.index.date)
data1_selected = sl.get_month_data(data1, 'close', 'Kospi지수')

In [49]:
data2 = pd.read_csv('./datasets/usd_to_krw.csv')
data2.set_index('time', inplace=True)
data2.index = pd.to_datetime(data2.index)
data2.index = pd.to_datetime(data2.index.date)
data2_selected = sl.get_month_data(data2, 'close', '원/달러 환율')

In [50]:
data3 = pd.read_csv('./datasets/yen_to_krw.csv')
data3.set_index('time', inplace=True)
data3.index = pd.to_datetime(data3.index)
data3.index = pd.to_datetime(data3.index.date)
data3_selected = sl.get_month_data(data3, 'close', '원/엔 환율')

In [51]:
data4 = pd.read_csv('./datasets/treasury_3yr.csv')
data4.set_index('time', inplace=True)
data4.index = pd.to_datetime(data4.index)
data4.index = pd.to_datetime(data4.index.date)
data4_selected = sl.get_month_data(data4, 'close', '국고채 3년 금리(%)')

In [52]:
data5 = pd.read_csv('./datasets/treasury_10yr.csv')
data5.set_index('time', inplace=True)
data5.index = pd.to_datetime(data5.index)
data5.index = pd.to_datetime(data5.index.date)
data5_selected = sl.get_month_data(data5, 'close', '국고채 10년 금리(%)')

In [53]:
data6 = pd.read_csv('./datasets/KOSPI_PER.csv', encoding='euc-kr')
data6['시점'] = data6['시점'].astype(str)
data6.loc[data6['시점'].str.contains('\.1$'), '시점'] = data6[data6['시점'].str.contains('\.1$')]['시점'].apply(lambda x: x[:-2] + '.10')
data6 = data6.set_index('시점').rename_axis('time')
data6.index = pd.to_datetime(data6.index)
data6.index = pd.to_datetime(data6.index.date)
data6_selected = sl.get_month_data(data6, 'KOSPI', 'kospi_per')

# data6 = data6.set_index('시점').rename_axis('time')
# data6.index = data6.index.str.replace('.', '-')

# data6['시점'] = pd.to_datetime(data6['시점'], format='%Y.%m')
# data6['시점'].data6['시점'].strftime('%Y-%m-%d')
# data6.index = pd.to_datetime(data6.index, format='%Y.%m')
# data6.index = pd.to_datetime(data6.index.date)
# data6_selected = sl.get_month_data(data6, 'KOSPI', 'kospi_per')

In [54]:
data7 = pd.read_csv('./datasets/KOSPI_PBR.csv', encoding='euc-kr')
data7['시점'] = data7['시점'].astype(str)
data7.loc[data7['시점'].str.contains('\.1$'), '시점'] = data7[data7['시점'].str.contains('\.1$')]['시점'].apply(lambda x: x[:-2] + '.10')
data7 = data7.set_index('시점').rename_axis('time')
data7.index = pd.to_datetime(data7.index)
data7.index = pd.to_datetime(data7.index.date)
data7_selected = sl.get_month_data(data7, 'KOSPI', 'kospi_pbr')

In [55]:
data8 = pd.read_csv('./datasets/Vkospi.csv')
data8.set_index('일자', inplace=True)
data8.index = pd.to_datetime(data8.index)
data8.index = pd.to_datetime(data8.index.date)
data8_selected = sl.get_month_data(data8, '종가', 'vkospi200')

In [56]:
data9 = pd.read_csv('./datasets/G10 ESI.csv')
data9.set_index('date', inplace=True)
data9.index = pd.to_datetime(data9.index)
data9.index = pd.to_datetime(data9.index.date)
data9_selected = sl.get_month_data(data9, 'number', 'g10_esi(%)')

In [57]:
data10 = pd.read_csv('./datasets/wti_lag.csv')
data10.set_index('DATE', inplace=True)
data10.index = pd.to_datetime(data10.index)
data10.index = pd.to_datetime(data10.index.date)
data10_selected = sl.get_month_data(data10, 'WTISPLC', 'wti')

In [58]:
data11 = pd.read_csv('./datasets/ustb_2y_lag.csv')
data11.set_index('DATE', inplace=True)
data11.index = pd.to_datetime(data11.index)
data11.index = pd.to_datetime(data11.index.date)

data11['DGS2'] = data11['DGS2'].str.replace('.', '')
data11['DGS2'] = data11['DGS2'].apply(lambda x: x.ljust(4, '0'))
data11['DGS2'] = data11['DGS2'].astype(float)
data11['DGS2'] = data11['DGS2']/1000
data11['DGS2'] = data11['DGS2'].replace(0, np.nan)

data11_selected = sl.get_month_data(data11, 'DGS2', 'ustb_2y(%)')

# data11['DGS2'] = data11['DGS2'].str.replace(',', '.').astype(float)
# data11['DGS2'] = pd.to_numeric(data11['DGS2'])
# data11['DGS2'] = data11['DGS2'].astype(float)

# data11_selected = sl.get_month_data(data11, 'DGS2', 'ustb_2y')

In [59]:
data12 = pd.read_csv('./datasets/ustb_10y_lag.csv')
data12.set_index('DATE', inplace=True)
data12.index = pd.to_datetime(data12.index)
data12.index = pd.to_datetime(data12.index.date)

data12['DGS10'] = data12['DGS10'].str.replace('.', '')
data12['DGS10'] = data12['DGS10'].apply(lambda x: x.ljust(4, '0'))
data12['DGS10'] = data12['DGS10'].astype(float)
data12['DGS10'] = data12['DGS10']/1000
data12['DGS10'] = data12['DGS10'].replace(0, np.nan)

data12_selected = sl.get_month_data(data12, 'DGS10', 'ustb_10y(%)')

In [60]:
data13 = pd.read_csv('./datasets/ustips_10y_lag.csv')
data13.set_index('DATE', inplace=True)
data13.index = pd.to_datetime(data13.index)
data13.index = pd.to_datetime(data13.index.date)

data13['DFII10'] = data13['DFII10'].str.replace('.', '')
data13['DFII10'] = data13['DFII10'].apply(lambda x: x.ljust(4, '0'))
data13['DFII10'] = data13['DFII10'].astype(float)
data13['DFII10'] = data13['DFII10']/1000
data13['DFII10'] = data13['DFII10'].replace(0, np.nan)

data13_selected = sl.get_month_data(data13, 'DFII10', 'ustips_10y(%)')

In [61]:
data14 = pd.read_csv('./datasets/vix_lag.csv')
data14.set_index('DATE', inplace=True)
data14.index = pd.to_datetime(data14.index)
data14.index = pd.to_datetime(data14.index.date)

data14['VIXCLS'] = data14['VIXCLS'].str.replace('.', '')
data14['VIXCLS'] = data14['VIXCLS'].apply(lambda x: x.ljust(4, '0'))
data14['VIXCLS'] = data14['VIXCLS'].astype(float)
data14['VIXCLS'] = data14['VIXCLS']/100
data14['VIXCLS'] = data14['VIXCLS'].replace(0, np.nan)

data14_selected = sl.get_month_data(data14, 'VIXCLS', 'vix(%)')

In [62]:
data15 = pd.read_csv('./datasets/EPU index.csv')
data15.set_index('DATE', inplace=True)
data15.index = pd.to_datetime(data15.index)
data15.index = pd.to_datetime(data15.index.date)
data15_selected = sl.get_month_data(data15, 'USEPUINDXD', 'EPU index')

In [63]:
data16 = pd.read_csv('./datasets/ism_manu_lag.csv')
data16.set_index('date', inplace=True)
data16.index = pd.to_datetime(data16.index)
data16.index = pd.to_datetime(data16.index.date)
data16_selected = sl.get_month_data(data16, 'number', 'usa_pmi')

In [64]:
data17 = pd.read_csv('./datasets/china_pmi_lag.csv')
data17.set_index('date', inplace=True)
data17.index = pd.to_datetime(data17.index)
data17.index = pd.to_datetime(data17.index.date)
data17_selected = sl.get_month_data(data17, 'number', 'china_pmi')

In [65]:
data18 = pd.read_csv('./datasets/export.csv')
data18.set_index('date', inplace=True)
data18.index = pd.to_datetime(data18.index)
data18.index = pd.to_datetime(data18.index.date)
data18_selected = sl.get_month_data(data18, 'number', 'kr_export(%)')

In [66]:
data19 = pd.read_csv('./datasets/Korea_CPI yoy.csv', encoding='euc-kr')
data19['시점'] = data19['시점'].astype(str)
data19.loc[data19['시점'].str.contains('\.1$'), '시점'] = data19[data19['시점'].str.contains('\.1$')]['시점'].apply(lambda x: x[:-2] + '.10')
data19 = data19.set_index('시점').rename_axis('time')
data19.index = pd.to_datetime(data19.index)
data19.index = pd.to_datetime(data19.index.date)
data19_selected = sl.get_month_data(data19, '전년동월비(%)', 'kr_cpi_yoy(%)')

In [67]:
data20 = pd.read_csv('./datasets/uscpi_yoy_lag.csv', encoding='euc-kr')
# data20['date'] = data20['date'].str.replace(r'\(.*\)', '', regex=True)
data20['date'] = data20['date'].str.replace(r'월.*$', '', regex=True)
data20['date'] = data20['date'].str.replace('년 ', '.')
data20['date'] = data20['date'].astype(str)

data20.set_index('date', inplace=True)
data20.index = pd.to_datetime(data20.index)
data20.index = pd.to_datetime(data20.index.date)
data20.sort_index(ascending=True, inplace=True)

data20['uscpi_yoy'] = data20['uscpi_yoy'].str.replace('%', '')
# data20['uscpi_yoy'] = data20['uscpi_yoy'].apply(lambda x: x.ljust(3, '0'))
data20['uscpi_yoy'] = data20['uscpi_yoy'].astype(float)
# data20['uscpi_yoy'] = data20['uscpi_yoy']/100
data20['uscpi_yoy'] = data20['uscpi_yoy'].replace(0, np.nan)

data20_selected = sl.get_month_data(data20, 'uscpi_yoy', 'uscpi_yoy(%)')
data20_selected = data20_selected.fillna(0)

In [68]:
data21 = data5.subtract(data4)
data21 = data21.dropna()
data21_selected = sl.get_month_data(data21, 'close', 'treasury_10_3_diff(%)')

In [69]:
data22 = pd.read_csv('./datasets/us_10_2_diff_lag.csv')
data22.set_index('DATE', inplace=True)
data22.index = pd.to_datetime(data22.index)
data22.index = pd.to_datetime(data22.index.date)

data22['T10Y2Y'] = data22['T10Y2Y'].apply(lambda x: x.ljust(5, '0') if len(x.replace('-', '')) <= 3 else x)
data22['T10Y2Y'] = data22['T10Y2Y'].str.replace('.', '')
data22['T10Y2Y'] = data22['T10Y2Y'].astype(float)
data22['T10Y2Y'] = data22['T10Y2Y']/100
data22['T10Y2Y'] = data22['T10Y2Y'].replace(0, np.nan)

data22_selected = sl.get_month_data(data22, 'T10Y2Y', 'us_10_2_diff(%)')

In [70]:
data23 = pd.read_csv('./datasets/us_e_infla_lag.csv')
data23.set_index('time', inplace=True)
data23.index = pd.to_datetime(data23.index)
data23.index = pd.to_datetime(data23.index.date)
data23_selected = sl.get_month_data(data23, 'close', 'us_e_infla(%)')

In [71]:
temp1 = data4_selected.copy()
temp1.rename(columns={'국고채 3년 금리(%)': 'kr_real_rate(%)'}, inplace=True)
temp2 = data19_selected.copy()
temp2.rename(columns={'kr_cpi_yoy(%)': 'kr_real_rate(%)'}, inplace=True)
data24_selected = temp1.subtract(temp2)

In [72]:
# date = default_date 
# date_list2 = []
# value_list = []
# for i in range(191):
#     j = 0
#     while True:
#         try:
#             temp = data1['close'].loc[data1.index==date].values[0]
#             break
#         except IndexError:  # 'index 0 is out of bounds for axis 0 with size 0' 에러를 잡음
#             temp = None

#         date = date + timedelta(days=1)
#         j = j+1
#     date_list2.append(date)
#     value_list.append(temp)

#     date = date -timedelta(days=j) +relativedelta(months=1)

In [73]:
dfs = data1_selected
for i in range(23):
    tem = globals()[f"data{i+2}_selected"]
    dfs = pd.concat([dfs, tem], axis=1)

In [80]:
dfs.to_csv('Macroeconomics_분기2.csv', encoding='utf-8-sig')

In [78]:
dfs

,Kospi지수,원/달러 환율,원/엔 환율,국고채 3년 금리(%),국고채 10년 금리(%),kospi_per,kospi_pbr,vkospi200,g10_esi(%),wti,...,EPU index,usa_pmi,china_pmi,kr_export(%),kr_cpi_yoy(%),uscpi_yoy(%),treasury_10_3_diff(%),us_10_2_diff(%),us_e_infla(%),kr_real_rate(%)
2007-06-01,1743.6000,928.128571,7.561238,5.224500,5.481500,14.90,1.61,20.586500,29.800000,67.48,...,50.801667,52.6,55.0,14.5,2.5,2.7,0.257000,0.128500,3.21462,2.724500
2007-09-01,1946.4800,929.210000,8.068450,5.388824,5.522353,16.99,1.80,31.315882,5.000000,79.93,...,79.891333,51.0,55.0,-1.1,2.3,2.0,0.133529,0.510000,2.57405,3.088824
2007-12-01,1897.1300,931.404762,8.260250,5.883684,5.831111,16.84,1.75,29.447222,6.633333,91.73,...,91.996129,49.0,53.3,14.8,3.6,4.3,-0.057778,0.980500,2.54378,2.283684
2008-03-01,1703.9900,981.332500,9.738300,5.151905,5.367143,15.39,1.59,30.740952,-9.500000,105.56,...,121.869032,48.3,54.4,18.4,3.9,4.0,0.215238,1.893000,1.93368,1.251905
2008-06-01,1674.9200,1031.642857,9.640619,5.668333,5.871500,13.31,1.40,23.795000,-20.925000,133.93,...,98.481000,49.8,53.3,16.4,5.5,4.2,0.192222,1.325714,2.72851,0.168333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-01,2757.6499,1220.370000,10.269478,2.360130,2.776739,12.58,1.12,22.550000,40.825000,108.50,...,186.614516,57.1,48.1,18.8,4.1,7.9,0.416609,0.413913,3.05770,-1.739870
2022-06-01,2332.6399,1277.864091,9.509182,3.444409,3.614636,10.17,0.92,22.056000,-7.033333,114.84,...,133.467333,53.0,51.7,5.3,6.0,8.6,0.170227,0.402381,4.22671,-2.555591
2022-09-01,2155.4900,1395.463636,9.724045,3.857864,3.867273,9.26,0.83,20.774000,-2.225000,84.26,...,109.556000,50.9,48.1,2.3,5.6,8.3,0.009409,-0.337619,4.17915,-1.742136
2022-12-01,2236.3999,1293.517727,9.572682,3.628364,3.539227,10.76,0.84,17.757143,19.150000,76.44,...,132.444516,48.4,49.0,-9.6,5.0,7.1,-0.089136,-0.672381,2.86812,-1.371636
2023-03-01,2476.8601,1303.870870,9.738783,3.475304,3.460043,11.97,0.93,17.904545,45.950000,73.28,...,140.280968,46.3,50.0,-13.8,4.2,6.0,-0.015261,-0.639565,2.07325,-0.724696

In [76]:
dfs.isna().sum()

Kospi지수                  0
원/달러 환율                  0
원/엔 환율                   0
국고채 3년 금리(%)             0
국고채 10년 금리(%)            0
kospi_per                0
kospi_pbr                0
vkospi200                0
g10_esi(%)               0
wti                      0
ustb_2y(%)               0
ustb_10y(%)              0
ustips_10y(%)            0
vix(%)                   0
EPU index                0
usa_pmi                  0
china_pmi                0
kr_export(%)             0
kr_cpi_yoy(%)            0
uscpi_yoy(%)             0
treasury_10_3_diff(%)    0
us_10_2_diff(%)          0
us_e_infla(%)            0
kr_real_rate(%)          0
dtype: int64